services:
  backend1:
    build: ./backend
    container_name: backend1
    ports:
      - 5001:5000
    networks:
      - loadbalancing

  backend2:
    build: ./backend
    container_name: backend2
    ports:
      - 5002:5000
    networks:
      - loadbalancing
  
  nginx:
    build: ./nginx
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
    networks:
      - loadbalancing
    depends_on:
      - backend1
      - backend2
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    #   - frontend-static:/usr/share/nginx/html
      

  # frontend:
  #   build: ./frontend
  #   container_name: frontend
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - frontend-static:/app/build

networks:
  loadbalancing:

# volumes:
#   frontend-static: